import type { Template, SizePreset, CanvasElement } from '@/types';

export const sizePresets: SizePreset[] = [
  { id: 'insta-square', name: 'Instagram 正方形', platform: 'Instagram', width: 1080, height: 1080, icon: 'Square' },
  { id: 'insta-portrait', name: 'Instagram 竖版', platform: 'Instagram', width: 1080, height: 1350, icon: 'Image' },
  { id: 'insta-story', name: 'Instagram 故事', platform: 'Instagram', width: 1080, height: 1920, icon: 'Smartphone' },
  { id: 'fb-post', name: 'Facebook 帖子', platform: 'Facebook', width: 1200, height: 630, icon: 'Monitor' },
  { id: 'twitter', name: 'Twitter 帖子', platform: 'Twitter', width: 1200, height: 675, icon: 'MessageSquare' },
  { id: 'xiaohongshu', name: '小红书', platform: '小红书', width: 1080, height: 1440, icon: 'BookOpen' },
  { id: 'wechat', name: '微信公众号', platform: '微信', width: 900, height: 383, icon: 'MessageCircle' },
  { id: 'douyin', name: '抖音', platform: '抖音', width: 1080, height: 1920, icon: 'Music' },
  { id: 'banner', name: '横幅广告', platform: '通用', width: 1200, height: 628, icon: 'RectangleHorizontal' },
  { id: 'poster', name: '海报', platform: '通用', width: 800, height: 1200, icon: 'FileImage' },
];

const createGradientBg = (colors: string[], width: number = 1080, height: number = 1080): CanvasElement => ({
  id: 'bg-gradient',
  type: 'shape',
  shapeType: 'rectangle',
  x: width / 2,
  y: height / 2,
  width,
  height,
  rotation: 0,
  opacity: 1,
  locked: true,
  visible: true,
  zIndex: 0,
  name: '背景',
  brandRole: 'background',
  fill: `linear-gradient(135deg, ${colors[0]} 0%, ${colors[1]} 100%)`,
  stroke: 'transparent',
  strokeWidth: 0,
  borderRadius: 0,
});

const createTitle = (content: string, y: number, color: string): CanvasElement => ({
  id: 'title-' + Math.random().toString(36).substring(2, 7),
  type: 'text',
  content,
  x: 540,
  y,
  width: 800,
  height: 120,
  rotation: 0,
  opacity: 1,
  locked: false,
  visible: true,
  zIndex: 10,
  name: '标题',
  brandRole: 'primary',
  fontSize: 72,
  fontFamily: 'Playfair Display',
  fontWeight: 700,
  color,
  textAlign: 'center',
  lineHeight: 1.2,
  letterSpacing: 2,
  shadow: { offsetX: 0, offsetY: 4, blur: 20, color: 'rgba(0,0,0,0.3)' },
});

const createSubtitle = (content: string, y: number, color: string): CanvasElement => ({
  id: 'subtitle-' + Math.random().toString(36).substring(2, 7),
  type: 'text',
  content,
  x: 540,
  y,
  width: 700,
  height: 80,
  rotation: 0,
  opacity: 1,
  locked: false,
  visible: true,
  zIndex: 9,
  name: '副标题',
  brandRole: 'secondary',
  fontSize: 32,
  fontFamily: 'Inter',
  fontWeight: 400,
  color,
  textAlign: 'center',
  lineHeight: 1.5,
  letterSpacing: 1,
});

const createBodyText = (content: string, y: number, color: string): CanvasElement => ({
  id: 'body-' + Math.random().toString(36).substring(2, 7),
  type: 'text',
  content,
  x: 540,
  y,
  width: 600,
  height: 100,
  rotation: 0,
  opacity: 0.9,
  locked: false,
  visible: true,
  zIndex: 8,
  name: '正文',
  brandRole: 'secondary',
  fontSize: 20,
  fontFamily: 'Inter',
  fontWeight: 300,
  color,
  textAlign: 'center',
  lineHeight: 1.8,
  letterSpacing: 0.5,
});

const createDecorativeShape = (x: number, y: number, size: number, color: string, zIndex: number): CanvasElement => ({
  id: 'shape-' + Math.random().toString(36).substring(2, 7),
  type: 'shape',
  shapeType: 'circle',
  x,
  y,
  width: size,
  height: size,
  rotation: 0,
  opacity: 0.6,
  locked: false,
  visible: true,
  zIndex,
  name: '装饰图形',
  brandRole: 'accent',
  fill: color,
  stroke: 'transparent',
  strokeWidth: 0,
  borderRadius: size / 2,
});

export const templates: Template[] = [
  {
    id: 'template-1',
    name: '简约新品发布',
    category: '产品推广',
    thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=minimalist%20product%20launch%20poster%20gradient%20blue%20orange&image_size=square',
    canvasState: {
      width: 1080,
      height: 1080,
      backgroundColor: '#ffffff',
      elements: [
        createGradientBg(['#667eea', '#764ba2']),
        createTitle('新品上市', 350, '#ffffff'),
        createSubtitle('NEW ARRIVAL · 限时优惠', 480, 'rgba(255,255,255,0.8)'),
        createBodyText('探索全新系列，发现属于你的独特风格\n立即选购享专属折扣', 600, 'rgba(255,255,255,0.9)'),
        createDecorativeShape(900, 150, 200, 'rgba(255,255,255,0.1)', 1),
        createDecorativeShape(100, 800, 150, 'rgba(255,255,255,0.1)', 1),
      ],
    },
  },
  {
    id: 'template-2',
    name: '活力促销活动',
    category: '活动营销',
    thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=vibrant%20sale%20promotion%20poster%20orange%20yellow&image_size=square',
    canvasState: {
      width: 1080,
      height: 1080,
      backgroundColor: '#ffffff',
      elements: [
        createGradientBg(['#f093fb', '#f5576c']),
        createTitle('限时特惠', 320, '#ffffff'),
        createSubtitle('全场低至 5 折起', 460, '#ffe066'),
        createBodyText('活动时间：6月15日 - 6月30日\n错过再等一年！', 600, '#ffffff'),
        createDecorativeShape(800, 200, 180, 'rgba(255,224,102,0.3)', 1),
        createDecorativeShape(150, 750, 120, 'rgba(255,255,255,0.2)', 1),
        {
          id: 'badge',
          type: 'shape',
          shapeType: 'circle',
          x: 850,
          y: 700,
          width: 150,
          height: 150,
          rotation: -15,
          opacity: 1,
          locked: false,
          visible: true,
          zIndex: 15,
          name: '徽章',
          fill: '#ffe066',
          stroke: 'transparent',
          strokeWidth: 0,
          borderRadius: 75,
        },
        {
          id: 'badge-text',
          type: 'text',
          content: '50% OFF',
          x: 925,
          y: 770,
          width: 120,
          height: 50,
          rotation: -15,
          opacity: 1,
          locked: false,
          visible: true,
          zIndex: 16,
          name: '折扣文字',
          fontSize: 28,
          fontFamily: 'Inter',
          fontWeight: 700,
          color: '#f5576c',
          textAlign: 'center',
          lineHeight: 1,
          letterSpacing: 1,
        },
      ],
    },
  },
  {
    id: 'template-3',
    name: '品牌故事',
    category: '品牌内容',
    thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elegant%20brand%20story%20poster%20dark%20blue%20gold&image_size=square',
    canvasState: {
      width: 1080,
      height: 1350,
      backgroundColor: '#0f172a',
      elements: [
        {
          id: 'bg',
          type: 'shape',
          shapeType: 'rectangle',
          x: 540,
          y: 675,
          width: 1080,
          height: 1350,
          rotation: 0,
          opacity: 1,
          locked: true,
          visible: true,
          zIndex: 0,
          name: '背景',
          fill: '#0f172a',
          stroke: 'transparent',
          strokeWidth: 0,
          borderRadius: 0,
        },
        {
          id: 'accent-line',
          type: 'shape',
          shapeType: 'rectangle',
          x: 540,
          y: 200,
          width: 100,
          height: 4,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          zIndex: 1,
          name: '装饰线',
          fill: '#d4af37',
          stroke: 'transparent',
          strokeWidth: 0,
          borderRadius: 2,
        },
        {
          id: 'title',
          type: 'text',
          content: '我们的故事',
          x: 540,
          y: 280,
          width: 800,
          height: 100,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          zIndex: 10,
          name: '标题',
          fontSize: 64,
          fontFamily: 'Playfair Display',
          fontWeight: 600,
          color: '#ffffff',
          textAlign: 'center',
          lineHeight: 1.2,
          letterSpacing: 8,
        },
        {
          id: 'subtitle',
          type: 'text',
          content: 'OUR STORY',
          x: 540,
          y: 400,
          width: 400,
          height: 40,
          rotation: 0,
          opacity: 0.7,
          locked: false,
          visible: true,
          zIndex: 9,
          name: '英文标题',
          fontSize: 20,
          fontFamily: 'Inter',
          fontWeight: 300,
          color: '#d4af37',
          textAlign: 'center',
          lineHeight: 1.5,
          letterSpacing: 6,
        },
        {
          id: 'body',
          type: 'text',
          content: '每一件作品都承载着我们对品质的执着追求\n\n源于对美好生活的热爱\n我们致力于创造独特而有温度的产品\n\n匠心独运，只为给你最好的体验',
          x: 540,
          y: 550,
          width: 700,
          height: 300,
          rotation: 0,
          opacity: 0.85,
          locked: false,
          visible: true,
          zIndex: 8,
          name: '正文',
          fontSize: 22,
          fontFamily: 'Inter',
          fontWeight: 300,
          color: '#cbd5e1',
          textAlign: 'center',
          lineHeight: 2,
          letterSpacing: 1,
        },
        {
          id: 'tagline',
          type: 'text',
          content: '— 匠心品质 · 美好生活 —',
          x: 540,
          y: 950,
          width: 500,
          height: 40,
          rotation: 0,
          opacity: 0.6,
          locked: false,
          visible: true,
          zIndex: 7,
          name: '标语',
          fontSize: 18,
          fontFamily: 'Inter',
          fontWeight: 300,
          color: '#d4af37',
          textAlign: 'center',
          lineHeight: 1.5,
          letterSpacing: 4,
        },
        createDecorativeShape(540, 1100, 100, 'rgba(212,175,55,0.2)', 1),
      ],
    },
  },
  {
    id: 'template-4',
    name: '清新夏日主题',
    category: '节日季节',
    thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=fresh%20summer%20theme%20poster%20green%20turquoise&image_size=square',
    canvasState: {
      width: 1080,
      height: 1080,
      backgroundColor: '#ffffff',
      elements: [
        createGradientBg(['#11998e', '#38ef7d']),
        createTitle('夏日清凉', 380, '#ffffff'),
        createSubtitle('SUMMER VIBES', 500, 'rgba(255,255,255,0.9)'),
        createBodyText('感受夏日的清新与活力\n让每一天都充满阳光', 620, 'rgba(255,255,255,0.95)'),
        createDecorativeShape(150, 150, 120, 'rgba(255,255,255,0.15)', 1),
        createDecorativeShape(900, 850, 160, 'rgba(255,255,255,0.1)', 1),
        createDecorativeShape(200, 900, 80, 'rgba(255,255,255,0.2)', 1),
      ],
    },
  },
  {
    id: 'template-5',
    name: '简约商务风',
    category: '商务办公',
    thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=minimalist%20business%20corporate%20poster%20navy%20blue&image_size=square',
    canvasState: {
      width: 1200,
      height: 628,
      backgroundColor: '#1e293b',
      elements: [
        {
          id: 'bg',
          type: 'shape',
          shapeType: 'rectangle',
          x: 600,
          y: 314,
          width: 1200,
          height: 628,
          rotation: 0,
          opacity: 1,
          locked: true,
          visible: true,
          zIndex: 0,
          name: '背景',
          fill: '#1e293b',
          stroke: 'transparent',
          strokeWidth: 0,
          borderRadius: 0,
        },
        {
          id: 'accent-bar',
          type: 'shape',
          shapeType: 'rectangle',
          x: 100,
          y: 150,
          width: 8,
          height: 300,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          zIndex: 1,
          name: '装饰条',
          fill: '#3b82f6',
          stroke: 'transparent',
          strokeWidth: 0,
          borderRadius: 4,
        },
        {
          id: 'title',
          type: 'text',
          content: '创新驱动未来',
          x: 150,
          y: 180,
          width: 600,
          height: 80,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          zIndex: 10,
          name: '标题',
          fontSize: 56,
          fontFamily: 'Playfair Display',
          fontWeight: 700,
          color: '#ffffff',
          textAlign: 'left',
          lineHeight: 1.2,
          letterSpacing: 1,
        },
        {
          id: 'subtitle',
          type: 'text',
          content: 'INNOVATION FOR THE FUTURE',
          x: 150,
          y: 280,
          width: 500,
          height: 40,
          rotation: 0,
          opacity: 0.7,
          locked: false,
          visible: true,
          zIndex: 9,
          name: '副标题',
          fontSize: 18,
          fontFamily: 'Inter',
          fontWeight: 400,
          color: '#94a3b8',
          textAlign: 'left',
          lineHeight: 1.5,
          letterSpacing: 3,
        },
        {
          id: 'body',
          type: 'text',
          content: '以科技为引擎，以创新为动力\n携手共创美好明天',
          x: 150,
          y: 350,
          width: 500,
          height: 80,
          rotation: 0,
          opacity: 0.9,
          locked: false,
          visible: true,
          zIndex: 8,
          name: '正文',
          fontSize: 20,
          fontFamily: 'Inter',
          fontWeight: 300,
          color: '#cbd5e1',
          textAlign: 'left',
          lineHeight: 1.8,
          letterSpacing: 0.5,
        },
        {
          id: 'deco-circle-1',
          type: 'shape',
          shapeType: 'circle',
          x: 1000,
          y: 100,
          width: 250,
          height: 250,
          rotation: 0,
          opacity: 0.1,
          locked: false,
          visible: true,
          zIndex: 1,
          name: '装饰圆',
          fill: '#3b82f6',
          stroke: 'transparent',
          strokeWidth: 0,
          borderRadius: 125,
        },
        {
          id: 'deco-circle-2',
          type: 'shape',
          shapeType: 'circle',
          x: 1100,
          y: 400,
          width: 180,
          height: 180,
          rotation: 0,
          opacity: 0.15,
          locked: false,
          visible: true,
          zIndex: 1,
          name: '装饰圆2',
          fill: '#60a5fa',
          stroke: 'transparent',
          strokeWidth: 0,
          borderRadius: 90,
        },
      ],
    },
  },
  {
    id: 'template-6',
    name: '温馨祝福卡',
    category: '祝福问候',
    thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=warm%20greeting%20card%20pastel%20pink%20purple&image_size=square',
    canvasState: {
      width: 1080,
      height: 1440,
      backgroundColor: '#fdf2f8',
      elements: [
        createGradientBg(['#fbc2eb', '#a6c1ee'], 1080, 1440),
        createTitle('生日快乐', 400, '#1e293b'),
        {
          id: 'subtitle',
          type: 'text',
          content: 'HAPPY BIRTHDAY',
          x: 540,
          y: 550,
          width: 600,
          height: 50,
          rotation: 0,
          opacity: 0.7,
          locked: false,
          visible: true,
          zIndex: 9,
          name: '英文祝福',
          fontSize: 24,
          fontFamily: 'Inter',
          fontWeight: 400,
          color: '#64748b',
          textAlign: 'center',
          lineHeight: 1.5,
          letterSpacing: 4,
        },
        createBodyText('愿你的每一天都充满阳光与欢笑\n所有的美好都如期而至\n\n生日快乐！', 650, '#334155'),
        createDecorativeShape(200, 200, 100, 'rgba(255,255,255,0.5)', 1),
        createDecorativeShape(850, 300, 80, 'rgba(255,255,255,0.6)', 1),
        createDecorativeShape(150, 1100, 120, 'rgba(255,255,255,0.4)', 1),
        createDecorativeShape(900, 1000, 90, 'rgba(255,255,255,0.5)', 1),
      ],
    },
  },
];
